compute_environment: LOCAL_MACHINE
distributed_type: NO
mixed_precision: bf16 # should always be true
num_machines: 1
machine_rank: 0
num_processes: 1
use_cpu: false
main_process_port: 29500
deepspeed_config: {}
fsdp_config: {}
main_training_function: main
debug: true
downcast_bf16: 'no'
use_cpu: false