debug: true
live_metrics: true
dataset_path: null  #datasets/apachejit/apachejit_llm_small_struc.jsonl
model_path: LLMs/pretrained/causal-lm/meta-llama/Llama-3.1-8B
quant: true
lora: true
bf16: true # should always be true
gradient_checkpointing: true
continue_from_dir: false
truncation_len: 1000
chunking_len: 100
