debug: true
live_metrics: true
dataset_path: /speed-scratch/a_s87063/repos/perf-pilot/datasets/jit_dp/apachejit_llm_small_struc.jsonl
model_path: /speed-scratch/a_s87063/repos/perf-pilot/LLMs/pretrained/causal-lm/meta-llama/Meta-Llama-3-8B
quant: true
lora: true
bf16: true
gradient_checkpointing: true
continue_from_dir: null
truncation_len: 75
chunking_len: 65
