debug: true
live_metrics: true
dataset_path: datasets/jit_defects4j/jit_defects4j_small_llm_struc.jsonl
model_path: LLMs/pretrained/causal-lm/meta-llama/Llama-3.1-8B
quant: true
lora: true
mixed_precision: true # should always be true
gradient_checkpointing: true
continue_from_dir: false
truncation_len: 20000
chunking_len: 5000
