debug: true
live_metrics: true
dataset_path: /home/a_s87063/repos/perf-pilot/datasets/jit_dp/apachejit_llm_small_struc.jsonl
model_path: /home/a_s87063/repos/perf-pilot/LLMs/pretrained/causal-lm/meta-llama/Llama-3.1-8B
quant: true
lora: true
bf16: true
gradient_checkpointing: true
continue_from_dir: false
truncation_len: 300
chunking_len: 200
