debug: null
live_metrics: true
dataset_path: /speed-scratch/a_s87063/repos/perf-pilot/datasets/mozilla_perf/perf_llm_struc.jsonl
model_path: /speed-scratch/a_s87063/repos/perf-pilot/LLMs/pretrained/sequence-classification/meta-llama/Llama-3.1-8B
class_imbalance_fix: focal_loss
threshold: null
quant: true
lora: true
bf16: true
gradient_checkpointing: true
continue_from_dir: null
selection_metric: recall@top_30%
truncation_len: 40000
