debug: null
live_metrics: true
dataset_path: datasets/mozilla_perf/perf_llm_struc.jsonl
model_path: LLMs/pretrained/sequence-classification/microsoft/codebert-base
class_imbalance_fix: focal_loss
threshold: null
quant: null
lora: null
bf16: true # should always be true
gradient_checkpointing: true
continue_from_dir: null
selection_metric: recall@top_30%
truncation_len: null
