debug: true
live_metrics: true
dataset_path: /home/a_s87063/repos/perf-pilot/datasets/jit_dp/apachejit_llm_small_struc.jsonl
model_path: /home/a_s87063/repos/perf-pilot/LLMs/pretrained/sequence-classification/meta-llama/Llama-3.1-8B
class_imbalance_fix: oversampling
threshold: null
quant: true
lora: true
bf16: true
gradient_checkpointing: true
continue_from_dir: false
selection_metric: recall@top_30%
truncation_len: 20000
