debug: true
live_metrics: true
dataset_path: /speed-scratch/a_s87063/repos/perf-pilot/datasets/jit_dp/apachejit_llm_small_struc_ast_meta.jsonl
model_path: /speed-scratch/a_s87063/repos/perf-pilot/LLMs/pretrained/sequence-classification/microsoft/codebert-base
class_imbalance_fix: focal_loss
threshold: null
quant: null
lora: null
bf16: true
gradient_checkpointing: true
continue_from_dir: null
selection_metric: recall@top_30%
truncation_len: null
