debug: true
live_metrics: true
dataset_path: datasets/apachejit/apachejit_llm_small_struc.jsonl
model_path: LLMs/pretrained/sequence-classification/meta-llama/Llama-3.1-70B
class_imbalance_fix: oversampling
threshold: null
quant: true
lora: true
bf16: true # should always be true
gradient_checkpointing: true
continue_from_dir: false
selection_metric: recall@top_30%
truncation_len: 20000
chunking_len: null