debug: true
live_metrics: true
dataset_path: datasets/jit_defects4j/jit_defects4j_total_llm_struc.jsonl
model_path: LLMs/pretrained/sequence-classification/meta-llama/Llama-3.1-8B
class_imbalance_fix: oversampling
threshold: null
quant: true
lora: true
mixed_precision: true # should always be true
gradient_checkpointing: true
continue_from_dir: false
selection_metric: f1  # recall@top_30%
truncation_len: 20000
chunking_len: null