debug: true
task_type: seq_cls    # seq_cls   # clm
live_metrics: true
dataset_path: datasets/apachejit/apachejit_total_llm_struc.jsonl   # datasets/apachejit/apachejit_small_llm_struc.jsonl   # datasets/jit_defects4j/jit_defects4j_small_llm_struc.jsonl
model_path: LLMs/snapshots/meta-llama/Llama-3.1-8B    # LLMs/snapshots/meta-llama/Llama-3.1-8B    # LLMs/pretrained/sequence-classification/llama3.1_apachejit
quant: false
lora: false
flash_attn_2: true
mixed_precision: bf16
truncation_len: null       # 40000     # 22000
chunking_len: null           # only for clm
class_imbalance_fix: oversampling     # oversampling
threshold: null
selection_metric: f1       #f1   # recall@top_30%  -  only for seq_ls
add_new_tokens: true
slurm_tmpdir_env: SLURM_TMPDIR   # SLURM_TMPDIR   # TMPDIR
continue_from_dir: null   # /home/alis/links/scratch/repos/perf-pilot/llama/training/run_2025-09-11_13-54-25/output
learning_rate: 1e-5  
num_train_epochs: 3
weight_decay: 0.01
resampling_ratio: 0.7
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
gradient_accumulation_steps: 32
lr_warmup_ratio: 0.05
eval_steps: 5
logging_steps: 5
save_steps: 50