debug: false
task_type: seq_cls    # seq_cls   # clm
live_metrics: true
dataset_path: datasets/jit_defects4j/jit_defects4j_small_llm_struc.jsonl   # datasets/apachejit/apachejit_small_llm_struc.jsonl   # datasets/jit_defects4j/jit_defects4j_small_llm_struc.jsonl
model_path: LLMs/pretrained/sequence-classification/llama3.1_jit_defects4j    # LLMs/snapshots/meta-llama/Llama-3.1-8B    # LLMs/pretrained/sequence-classification/test
quant: true
lora: true
mixed_precision: bf16
continue_from_dir: false
truncation_len: 22000
chunking_len: 4000           # only for clm
class_imbalance_fix: oversampling
threshold: null
selection_metric: f1        # recall@top_30%  -  only for seq_ls