debug: false
task_type: seq_cls    # seq_cls   # clm
live_metrics: true
dataset_path: datasets/apachejit/apachejit_small_llm_struc.jsonl   # datasets/apachejit/apachejit_small_llm_struc.jsonl   # datasets/jit_defects4j/jit_defects4j_small_llm_struc.jsonl
model_path: LLMs/snapshots/meta-llama/Llama-3.1-70B    # LLMs/snapshots/meta-llama/Llama-3.1-8B    # LLMs/pretrained/sequence-classification/llama3.1_apachejit
quant: true
lora: true
flash_attn_2: true
mixed_precision: bf16
continue_from_dir: false
truncation_len: 40000       # 40000
chunking_len: null           # only for clm
class_imbalance_fix: oversampling     # oversampling
threshold: null
selection_metric: recall@top_30%       #f1   # recall@top_30%  -  only for seq_ls
add_new_tokens: true
slurm_tmpdir_env: SLURM_TMPDIR   # SLURM_TMPDIR   # TMPDIR
continue_from_dir: null   # /home/alis/links/scratch/repos/perf-pilot/llama/training/run_2025-09-11_13-54-25/output
